# Generated by Django 4.0.1 on 2022-01-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magazine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='magazine',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
