# Generated by Django 4.0 on 2022-01-11 13:06

import courses.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('reply', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='نام دوره', max_length=255, verbose_name='name')),
                ('img', models.ImageField(blank=True, null=True, upload_to='course/images/')),
                ('price', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
                ('class_history', models.JSONField(default=dict, validators=[courses.validators.JSONSchemaValidator(limit_value={'properties': {'students': {'type': 'array'}}, 'required': ['students'], 'schema': 'Course history schema', 'type': 'object'})])),
            ],
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('season_chapter', models.SmallIntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CourseChapterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='course/contents/')),
                ('type_content', models.CharField(choices=[('video', 'Video'), ('picture', 'Picture'), ('voice', 'Voice'), ('pdf', 'PDF')], max_length=10)),
                ('update_field', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
    ]
