# Generated by Django 4.0 on 2022-01-11 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursestudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile'),
        ),
        migrations.AddField(
            model_name='coursechaptermedia',
            name='course_chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursechapter'),
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.coursecategory'),
        ),
        migrations.AddField(
            model_name='course',
            name='mentor',
            field=models.ManyToManyField(related_name='mentors', to='user.Mentor'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students', through='courses.CourseStudent', to='user.Profile'),
        ),
        migrations.AddField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(blank=True, to='courses.Tag'),
        ),
        migrations.AddField(
            model_name='comment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='courses.course'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('user', 'course'), name='unique comment_to_course'),
        ),
    ]
