# Generated by Django 4.0 on 2022-01-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursechaptermedia',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
    ]
