# Generated by Django 4.0 on 2021-12-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_tag_remove_course_subject_course_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
