# Generated by Django 4.0 on 2021-12-14 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseChapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('season_chapter', models.SmallIntegerField()),
                ('content', models.TextField()),
            ],
        ),
        # migrations.CreateModel(
        #     name='CourseStudent',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #     ],
        # ),
        migrations.AddField(
            model_name='course',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='course/images/'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, verbose_name='نام'),
        ),
        migrations.CreateModel(
            name='CourseChapterMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.FileField(upload_to='course/contents/')),
                ('type_content', models.CharField(choices=[('video', 'Video'), ('picture', 'Picture'), ('voice', 'Voice'), ('pdf', 'PDF')], max_length=10)),
                ('update_field', models.DateTimeField(auto_now=True)),
                ('course_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursechapter')),
            ],
        ),
        migrations.AddField(
            model_name='coursechapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
    ]
