# Generated by Django 4.0 on 2021-12-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursechapter_coursestudent_course_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(blank=True, null=True, to='courses.Tag'),
        ),
    ]
