# Generated by Django 4.0 on 2021-12-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='tag',
            field=models.ManyToManyField(blank=True, to='courses.Tag'),
        ),
    ]
