# Generated by Django 4.0 on 2021-12-28 15:22

import courses.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_phone_number'),
        ('courses', '0008_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='subject',
        ),
        migrations.AddField(
            model_name='course',
            name='class_history',
            field=models.JSONField(default=dict, validators=[courses.validators.JSONSchemaValidator(limit_value={'properties': {'students': {'type': 'array'}}, 'required': ['students'], 'schema': 'Course history schema', 'type': 'object'})]),
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='students', through='courses.CourseStudent', to='user.Profile'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mentor',
            field=models.ManyToManyField(related_name='mentors', to='user.Mentor'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(help_text='نام دوره', max_length=255, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.profile'),
        ),
    ]
