# Generated by Django 4.0 on 2022-01-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_comment_comment_unique comment_to_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_history',
            field=models.JSONField(),
        ),
    ]
