# Generated by Django 3.2.9 on 2021-12-10 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_auto_20211210_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='users/'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='category',
            field=models.ManyToManyField(to='todo_app.Category'),
        ),
    ]
