# Generated by Django 3.2.9 on 2021-12-17 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_auto_20211210_0856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['headline'],
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PublicationArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField()),
                ('Publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.publication')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo_app.article')),
            ],
            options={
                'db_table': 'publicatin_article',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='publications',
            field=models.ManyToManyField(through='todo_app.PublicationArticle', to='todo_app.Publication'),
        ),
    ]
