# Generated by Django 3.2.9 on 2021-12-17 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0008_rename_publication_publicationarticle_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicationarticle',
            old_name='data',
            new_name='published_date',
        ),
    ]
