# Generated by Django 4.0 on 2021-12-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_mentor_alter_profile_options_profile_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Mentor'},
        ),
    ]
